databases-week3
ReenuMary/hyf-homework pull request #15
Opened 2022-08-30 10:38 UTC by ReenuMary

2022-09-04 21:03 UTC, Elia-Git requested changes
Few comments for a quick fix. Thanks!

2022-09-04 21:03 UTC, Elia-Git commented on databases/week3/meal_sharing_queries.sql
> +GROUP BY reservation.meal_id;
What are you aiming to get here..? I can't see which meal is fully or partially booked. Each meal has a limited nr. of spots to reserve &we need to know which meals are not fully booked/reserved..?
Try this instead & see how big a difference it makes in the result
```
SELECT meal.*, sum(reservation.number_of_guests) AS Total_reserved_yet
FROM meal
JOIN reservation ON meal.id = reservation.meal_id
GROUP BY reservation.meal_id
HAVING meal.max_reservations > Total_reserved_yet;
```

2022-09-04 21:03 UTC, Elia-Git commented on databases/week3/meal_sharing_queries.sql
> +GROUP BY review.stars, review.meal_id;
Here why do we need to count stars? We can specify when we call a meal got a good, bad or moderate review, then we can filter.
In this case, if I say reviews>10 -good, review between 5-9 moderate & reviews <5 could be bad reviewed
and we can try like below
```
SELECT meal.*,review.stars AS Stars_recieved FROM meal
JOIN review ON meal.id=review.Meal_Id
WHERE review.stars>9;
```

2022-09-06 10:09 UTC, shravanipagilla reviewed
👍  I hope you can understand my comments otherwise just  let me know @ReenuMary .. 
thank you .

2022-09-06 10:09 UTC, shravanipagilla commented on databases/week3/meal_sharing_create_db.sql
> +
Hej @ReenuMary  ,can you upload the .png  file  :)  ..   if you can ...

2022-09-06 10:09 UTC, shravanipagilla commented on databases/week3/meal_sharing_queries.sql
> +description ='This delectable Indian Vegetable Korma recipe is loaded with potatoes, tomatoes, carrots, peas, and green beans. Have plenty of naan to dip!'
:) yummy food...

2022-09-06 10:09 UTC, shravanipagilla commented on databases/week3/meal_sharing_queries.sql
> +SELECT * FROM meal WHERE price<=200;
👍

2022-09-06 10:09 UTC, shravanipagilla commented on databases/week3/meal_sharing_queries.sql
> +GROUP BY reservation.meal_id;
👍

2022-09-06 10:09 UTC, shravanipagilla commented on databases/week3/meal_sharing_queries.sql
> +SELECT review.meal_id,meal.title,review.stars,COUNT(review.stars) AS 'No of reviews with this rating' FROM review
Can you write AS is little short form , it is just my suggestion . if you want .. :)

2022-10-08 18:16 UTC, merged